services:
  voicenote-pwa:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: voicenote-pwa:latest
    container_name: voicenote-pwa
    restart: unless-stopped
    ports:
      - "8081:80"
    networks:
      - amayu-network

networks:
  amayu-network:
    external: true
